scenario_index:
    path: /
    methods: [GET]
    defaults:
        _controller: AppBundle:Default:scenarioIndex

scenario_show:
    path: /{scenario_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:Default:scenarioShow
    requirements:
        scenario_id: '\\d+'
