AppBundle\Entity\User:
    type:  entity
    table: user
    oneToMany:
        decks:
            targetEntity: Deck
            orderBy: {'dateUpdate':'DESC'}
            mappedBy: user
            cascade: ["remove"]
        decklists:
            targetEntity: Decklist
            mappedBy: user
        comments:
            targetEntity: Comment
            orderBy: {'dateCreation':'DESC'}
            mappedBy: user
        reviews:
            targetEntity: Review
            orderBy: {'dateCreation':'DESC'}
            mappedBy: user
    manyToMany:
        favorites:
            targetEntity: Decklist
            mappedBy: favorites
            cascade: ["remove"]
        votes:
            targetEntity: Decklist
            mappedBy: votes
            cascade: ["remove"]
        reviewvotes:
            targetEntity: Review
            mappedBy: votes
            cascade: ["remove"]
        following:
            targetEntity: User
            mappedBy: followers
        followers:
            targetEntity: User
            inversedBy: following
            joinTable:
                name: follow
                joinColumns:
                    following_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    follower_id:
                        referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
        reputation:
            type: integer
            nullable: false
        faq:
            type: boolean
            nullable: true
            options:
                default: false
        resume:
            type: text
            nullable: true
        color:
            type: string
            length: 255
            nullable: true
        donation:
            type: integer
            nullable: false
        isNotifAuthor:
            type: boolean
            nullable: false
            column: is_notif_author
            options:
                default: true
        isNotifCommenter:
            type: boolean
            nullable: false
            column: is_notif_commenter
            options:
                default: true
        isNotifMention:
            type: boolean
            nullable: false
            column: is_notif_mention
            options:
                default: true
        isNotifFollow:
            type: boolean
            nullable: false
            column: is_notif_follow
            options:
                default: true
        isNotifSuccessor:
            type: boolean
            nullable: false
            column: is_notif_successor
            options:
                default: true
        isShareDecks:
            type: boolean
            nullable: false
            column: is_share_decks
            options:
                default: false
        isNewUI:
            type: boolean
            nullable: false
            column: is_new_ui
            options:
                default: false
        isAdmin:
            type: boolean
            nullable: false
            column: is_admin
            options:
                default: false
        ownedPacks:
            type: string
            length: 512
            nullable: true
        isShareCollection:
            type: integer
            nullable: false
            column: is_share_collection
            options:
                default: 0
        showIconAspect:
            type: integer
            nullable: false
            column: show_icon_aspect
            options:
                default: 0
        showArchetype:
            type: integer
            nullable: false
            column: show_archetype
            options:
                default: 0
        showTheme:
            type: text
            nullable: true
            column: show_theme
        showLegacySchOrder:
            type: integer
            nullable: true
            column: show_legacy_sch_order
            options:
                default: 0
        showTagDefault:
            type: integer
            nullable: false
            column: show_tag_default
            options:
                default: 1
        printFaction:
            type: integer
            nullable: false
            column: print_faction
            options:
                default: 1
        printType:
            type: integer
            nullable: false
            column: print_type
            options:
                default: 1
        printTag:
            type: integer
            nullable: false
            column: print_tag
            options:
                default: 1
        printSide:
            type: integer
            nullable: false
            column: print_side
            options:
                default: 0
        showCurrentOnlyDefault:
            type: integer
            nullable: false
            column: show_current_only_default
            options:
                default: 0
        lastActiveAt:
            type: datetime
            nullable: true
            column: last_active_at
        visual_options:
            type: text
            nullable: false
            column: visual_options
            options:
                default: '{"enhanced_decklistview":0}'
